import type { APIRoute } from "astro";
import { getBlogPosts, getCourses, getNewsList } from "@/lib/frappe";
import { originFor, renderUrlset, xmlResponse, type SitemapEntry } from "@/lib/sitemap";
import { allCategoryHrefs } from "@/components/stocks/stock-categories";
// Generated by scripts/page-lastmod.mjs (predev/prebuild) from git history.
import pageLastmod from "@/lib/page-lastmod.json";

/**
 * Editorial sitemap: every static page plus the blog.
 *
 * This is what /sitemap.xml used to be. It moved here when the stock pages
 * arrived, because 22,000 instrument addresses do not belong in the same file
 * as the marketing site - see src/lib/sitemap.ts.
 */

/**
 * Routes that exist under src/pages but are deliberately kept out of the
 * sitemap: the error page, the theme's kitchen-sink demo, and /index2 -- a
 * near-duplicate of the homepage that would compete with "/" for the same
 * content. Add or remove entries here as pages come and go.
 */
const EXCLUDED = new Set(["/404", "/components", "/index2"]);

/**
 * Frappe reads a page length of 0 as "every row", so the blog and news lists
 * are never cut short. They were capped at 200 until the blog grew past it and
 * every post after the 200th quietly fell out of the sitemap.
 */
const ALL = 0;

/**
 * Static routes are discovered from the filesystem so newly added pages appear
 * automatically. Dynamic routes ("[slug]", "[id]") are skipped here and
 * expanded from their data source instead. The glob only matches .astro, so the
 * sitemap endpoints themselves are never listed.
 */
function staticRoutes(): { route: string; file: string }[] {
  const modules = import.meta.glob("./**/*.astro");

  return Object.keys(modules)
    .map((file) => {
      const route = file
        .replace(/^\./, "")
        .replace(/\.astro$/, "")
        .replace(/\/index$/, "/");
      return { route: route !== "/" && route.endsWith("/") ? route.slice(0, -1) : route, file };
    })
    .filter(({ route }) => !route.includes("[") && !EXCLUDED.has(route))
    .sort((a, b) => a.route.localeCompare(b.route));
}

export const GET: APIRoute = async ({ site, url }) => {
  const SITE = originFor(site, url);
  const entries: SitemapEntry[] = [];

  const lastmodByFile: Record<string, string> = pageLastmod;

  for (const { route, file } of staticRoutes()) {
    // The homepage is listed without a trailing slash, as Webflow listed it.
    entries.push({ loc: route === "/" ? SITE : `${SITE}${route}`, lastmod: lastmodByFile[file] });
  }

  // The sector, industry and market-cap landing pages under /stocks. Their
  // routes are dynamic, so the filesystem walk above skips them; the list is
  // static (stock-categories.ts), so no fetch is needed.
  for (const href of allCategoryHrefs()) {
    entries.push({ loc: `${SITE}${href}` });
  }

  // Blog articles are served by SSR routes, so they have to be enumerated from
  // Frappe. Guarded: if Frappe is unreachable the sitemap still ships with the
  // static pages rather than 500ing.
  try {
    const posts = await getBlogPosts(ALL);
    for (const post of posts) {
      entries.push({
        loc: `${SITE}/blog/${post.slug}`,
        lastmod: post.modifiedISO || post.publishedISO || undefined,
      });
    }
  } catch (error) {
    console.error("sitemap: could not load blog posts", error);
  }

  // News articles are SSR routes too, and enumerated the same guarded way.
  try {
    const articles = await getNewsList(ALL);
    for (const article of articles) {
      entries.push({
        loc: `${SITE}/news/${article.slug}`,
        lastmod: article.modifiedISO || article.publishedISO || undefined,
      });
    }
  } catch (error) {
    console.error("sitemap: could not load news articles", error);
  }

  // Course chapters, one URL each. The bare /courses/<course> address only
  // redirects to its first chapter, so it is left out.
  try {
    for (const course of await getCourses()) {
      for (const chapter of course.chapters) {
        entries.push({ loc: `${SITE}/courses/${course.slug}/${chapter.slug}` });
      }
    }
  } catch (error) {
    console.error("sitemap: could not load courses", error);
  }

  // Seminars are deliberately NOT listed. Each one drops off the site once its
  // grace window closes, so any URL published here would go stale within days
  // and leave crawlers chasing entries that no longer resolve to a live
  // listing. The detail pages stay reachable; they just aren't advertised.

  return xmlResponse(renderUrlset(entries));
};
